### ISSUE TITLE
An option for choosing between LIFO and FIFO ordering

### ISSUE THREAD

**Issue by ghost** [crossbeam-rs/crossbeam-deque#11]
Tokio and Rayon need an option for fair scheduling (processing elements in FIFO order rather than LIFO). While we do support FIFO ordering, our performance is not as good as it could be...

Here's what we've learned over time so far:

* `crossbeam-deque` was initially designed as a LIFO data structure (`Deque::push()` and `Deque::pop()` work with one end, while `Stealer::steal()` works with the other end). Later on, we've added support for FIFO ordering (fair scheduling) through the `Deque::steal()` method. That means our deque now supports both FIFO and LIFO processing at the same time.

* A minor observation: the method `Deque::stealer()` is not that useful. I've searched for all uses of `crossbeam-deque` and it seems most users simply do `let d = Deque::new(); let s = d.stealer()` anyway. The old constructor that returns `(Worker<T>, Stealer<T>)` was serving us just fine.

* There have been multiple requests for *steal-half* operation (i.e. *batched steal*). Unfortunately, Chase-Lev deques cannot implement it particularly efficiently, but we can still gain something from batching. By batching multiple steal operations together, we can execute `epoch::pin()` only once rather within each call to `steal()`. This should give us some performance wins.

* `CircBuf` by @jeehoonkang is faster than `crossbeam-deque` because it doesn't attempt to support the `Deque::pop()` operation at all - i.e. it is a FIFO-only data structure. Moreover, the lack of `Deque::pop()` allows it to implement a very efficient batched steal operation. @carllerche has expressed interest in using it in Tokio.

I'd like to propose the following:

1. Let's merge `crossbeam-deque` and `CircBuf` into a single data structure, but differentiate between the underlying implementations at runtime ("flavors"). The same idea is used in `std::sync::mpsc` and `crossbeam-channel`, where we have two completely different implementations for bounded and unbounded channels but behind the same interface. Java's `ForkJoinPool` supports LIFO and FIFO very similarly (see [here](https://github.com/netroby/jdk9-dev/blob/master/jdk/src/java.base/share/classes/java/util/concurrent/ForkJoinPool.java#L2191)).

2. Let's tweak the interface a little bit for simplicity.

3. Let's add support for batched stealing.

Finally, here's the interface I'm proposing:

```rust
// `Worker::push()`   - bottom
// `Worker::pop()`    - top
// `Stealer::steal()` - top
fn fifo() -> (Worker<T>, Stealer<T>);

// `Worker::push()`   - bottom
// `Worker::pop()`    - bottom
// `Stealer::steal(). - top
fn lifo() -> (Worker<T>, Stealer<T>);

// Pushes and pops elements.
struct Worker<T>;

// Steals an element.
struct Stealer<T>;

impl<T> Worker<T> {
    // Pushes an element.
    fn push(&self, value: T);

    // Pops an element.
    fn pop(&self) -> Option<T>;

    fn is_empty(&self) -> bool;
    fn len(&self) -> usize;
}

impl<T> Stealer<T> {
    // Steals an element.
    fn steal(&self) -> Steal<T>;

    // Steals a batch of elements.
    fn steal_batch(&self) -> Steal<Batch<T>>;

    fn is_empty(&self) -> bool;
    fn len(&self) -> usize;
}

enum Steal<T> {
    // The queue was empty.
    Empty,

    // Some data was stolen.
    Data(T),

    // The operation should be retried.
    Retry,
}

// A batch of elements.
//
// Internally, this should probably be just a wrapper around
// `SmallVec::<[T; 16]>::IntoIter`, or something similar.
struct Batch<T>;

impl<T> Iterator for Batch<T> {
    type Item = T;
}
```

The advantages of this design are:

* By choosing LIFO or FIFO strategy at construction (functions `lifo()` and `fifo()`), we can internally use the most optimal implementation (Chase-Lev vs `CircBuf`) for methods `push`, `pop`, `steal`, and `steal_batch`.

* The interface is simple. One can easily choose the appropriate scheduling strategy (FIFO or LIFO) at runtime - we have a single `Worker` and `Stealer` type for both. This will be quite handy in Rayon.

What do you think?

cc @carllerche @jeehoonkang

**Comment by carllerche** [comment]
I would also like to add that `CircBuf` not having any fences is also a selling point to me. I've been hitting TSAN warnings that I believe are false positives, but I am not 100% sure.

Re: merging within one structure, how do you differentiate the implementations internally? A condition or dyn dispatch? I assume you have measured the performance implications vs. just having separate data structures?

**Comment by ghost** [comment]
Just writing down another idea for the interface of `steal_batch`:

```rust
impl<T> Stealer<T> {
    fn steal_batch<E: Extend<T>>(container: &mut E);
}
```

This way we don't have to introduce `struct Batch` nor allocate needlessly when calling `steal_batch`.
