### ISSUE TITLE
NUMA & split-LLC topology awareness

### ISSUE THREAD

**Issue by farnoy** [crossbeam-rs/crossbeam-deque#16]
Hi, I have an open-ended question about the work-stealing algorithm.

In a NUMA environment, would it be beneficial to prioritize stealing items from queues in the same NUMA domain, to improve spatial locality and to utilize "near" memory better?

Would the same apply to a topology where Last Level Caches are further split within each NUMA node?

I'm looking for pointers as to which parts of the code should be modified to test this theory.

Example topology: 
![image](https://user-images.githubusercontent.com/345808/44283559-13a56780-a25f-11e8-809f-385c49a0dfb2.png)

**Comment by ghost** [comment]
Hi @farnoy, and sorry for the late reply.

Yes, I think it would be worth trying to prioritize stealing items from the "nearest" CPU core.

This crate, however, only provides concurrent data structures and isn't concerned with questions like these so they're kind of out of scope. Such questions are probably more related to crates like `tokio-threadpool` and `rayon-core`. But I would love to hear if you have any results nonetheless!

The two aforementioned crates provide schedulers that spawn threads, assign a deque to each thread, process tasks, steal tasks when needed, and so on. It might be beneficial to pin threads to CPU cores, figure out the NUMA layout, and try stealing from deques assigned to nearest cores first. At least that's something I'd suggest to do. :)

**Comment by farnoy** [comment]
I have noticed after posting that it would be out of scope for this project. I submitted an issue in rayon-core instead, but got no response yet. I guess you can close this issue as its not relevant.

Do you know of any research for a balancing scheme that does not rely on statically pinning threads to CPU cores? I'm wondering if there's a way to do it dynamically, "obeying" and adjusting to how the OS schedules these at runtime.

**Comment by ghost** [comment]
I'm not aware of any research on this topic, but here's a discussion you might find useful: https://github.com/golang/go/issues/18802

> I'm wondering if there's a way to do it dynamically, "obeying" and adjusting to how the OS schedules these at runtime.

You might try calling [`getcpu`](http://man7.org/linux/man-pages/man2/getcpu.2.html) to figure out which CPU core you're on and then poll queues in the appropriate order.

**Comment by farnoy** [comment]
Thanks for the response, I'll close it now.
