### ISSUE TITLE
Deque::shrink_to_fit support?

### ISSUE THREAD

**Issue by svartalf** [crossbeam-rs/crossbeam-deque#6]
During the `Deque::push` call boosts deque can allocate memory for inner buffer unlimitedly if stealers are too slow to read incoming data fast enough.

It would be nice to have [`Vec::shrink_to_fit`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.shrink_to_fit) method analog which can be used time to time (ex. when `Steal::Empty` variant is received from the stealer) in order to reduce allocated buffer size.

For example, following program is allocating around 4 gigabytes of memory on my notebook, which is okay while messages are pushed to deque, but kinda redundant when stealer had finished it's job.

```rust
extern crate crossbeam_deque;

use std::thread;
use crossbeam_deque::{Deque, Stealer, Steal};

fn writer(deque: Deque<String>) {
    for _ in 0..100_000_000 {
        deque.push("Hello world".to_string());
    }
}

fn reader(stealer: Stealer<String>) {
    loop {
        match stealer.steal() {
            Steal::Empty => {
                // Shrink deque here maybe?
                thread::sleep_ms(50);
            },
            Steal::Retry => {},
            Steal::Data(line) => {
                // I'm going to use `println!` here to emulate slow reader behaviour
                println!("{}", line);
            }
        }
    }
}

fn main() {
    let deque = Deque::<String>::with_min_capacity(1024);
    let stealer = deque.stealer();

    let writer = thread::spawn(move || { writer(deque) });
    let reader = thread::spawn(move || { reader(stealer) });

    writer.join().unwrap();
    reader.join().unwrap();
}
```

**Comment by ghost** [comment]
Unfortunately, we can't (as far as I'm aware of) shrink the underlying buffer from a stealer side. Only the worker side (`Deque`) can grow and shrink the buffer. At best, we could add method `Deque::shrink()`.

@jeehoonkang Any idea if it'd be possible to shrink the buffer inside `Stealer::steal()`?

**Comment by svartalf** [comment]
@stjepang well, I suppose I can solve my case with a combination of the `Deque::len()`, `Deque::capacity()` and `Deque::shrink()` methods, if is okay to add last two methods to deque.

I believe, `shrink` will not be very costly operation?

**Comment by ghost** [comment]
@svartalf 

I've just opened a pull request to add the methods you need: #9

> I believe, `shrink` will not be very costly operation?

It bears the costs of:

* allocation of the new buffer (relatively cheap)
* copying old elements into the new buffer (cheap if there are few, costly if there are many)
* adding the old buffer into the GC (cheap)

**Comment by svartalf** [comment]
@stjepang wow, that was amazingly fast :)

I'd also found #7 which is kinda easier to use for me, but I'm not sure if automatic buffer resize will suit everyone needs, at least [`Vec`](https://github.com/rust-lang/rust/blob/master/src/liballoc/vec.rs#L1055) is not doing this and there might be a reasons (I don't know them though).

Any way, I'd tested #9 quickly and it seems great!

**Comment by ghost** [comment]
I've just published version 0.3.0 with the new methods. See [CHANGELOG.md](https://github.com/crossbeam-rs/crossbeam-deque/blob/master/CHANGELOG.md) for the full list of changes.

**Comment by ghost** [comment]
@svartalf I'm doing some research and thinking about the current interface of this crate.

Just two questions:

1. Have you found any of the new methods useful (`shrink_to_fit`, `with_min_capacity`, `min_capacity`, `capacity`)?
2. Do you perhaps have a link to your code where `crossbeam-deque` is used?

**Comment by svartalf** [comment]
@stjepang well, I used `shrink_to_fit` for my pet project, but it is currently on hold right now, so it is not even in production.

I believe that I can't share source code, but basically `crossbeam-deque` is used as a communication queue between two threads, where first thread works as a FFI interface and should insert data into this queue ASAP, and second thread is just processing data from queue in some manner.
